apiVersion: 1.0.0
kind: ProcessDefinition
process:
  atrn: "nrn:process:nape/software-processes:rust-ci/sourcecode-integration"
  short: "Rust CI Control Activities"
  description: |
    "This is the complete process required to integrate a source code change for a rust application 
    back into the trunk, or main branch, of the source code repository."
procedures:
  - name: "peer-review"
    short: "Peer Review"
    description: "This procedure verifies that a peer review was completed to expectation"
    expect-evidence:
      - "./evidence/peer-review/peer-review.json"
    activity:
      - name: "at-least-two-reviewers"
        short: "Two (2) Reviewer Approval"
        description: "There are at least two (2) peer reviews who approved the merge request."
        test: "./procedures/peer-review/at-least-two-reviewers.py"
        evidence: "./evidence/peer-review/peer-review.json"
      - name: "requester-not-a-reviewer"
        short: "Requester is not Approver"
        description: "The person who initiated the merge request is not one of the people who approved the merge request."
        test: "./procedures/peer-review/requester-not-a-reviewer.py"
        evidence: "./evidence/peer-review/peer-review.json"